# Generated by Django 2.2.7 on 2024-02-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_savedcarts'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasta',
            name='pasta_gif',
            field=models.CharField(default='pasta_img', max_length=200),
        ),
    ]
