# Generated by Django 2.2.7 on 2024-02-22 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_pasta_pasta_gif'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasta',
            name='pasta_gif',
            field=models.CharField(default=datetime.datetime.now, max_length=200),
        ),
    ]
