# Generated by Django 2.2.7 on 2024-02-22 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_pasta_pasta_gif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasta',
            name='pasta_gif',
        ),
    ]
