# Generated by Django 2.2.7 on 2024-02-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_pasta_pasta_gif'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasta',
            name='img',
            field=models.CharField(default='C:\\Users\\aksha\\Downloads\\Food-Ordering_Django\\Food-Ordering_Django\\orders\\static\\orders\\images\\pastas\\orzos.jpg', max_length=200),
            preserve_default=False,
        ),
    ]
