# Generated by Django 2.2.7 on 2024-02-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_pasta_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='salad',
            name='img',
            field=models.CharField(default='orders\\images\\pastas', max_length=200),
            preserve_default=False,
        ),
    ]
