# Generated by Django 2.2.7 on 2024-02-23 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_salad_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasta',
            name='img',
        ),
    ]
