# Generated by Django 2.2.7 on 2024-02-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20240226_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasta',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='salad',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sicilianpizza',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sub',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
