# Generated by Django 2.2.7 on 2024-02-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20240226_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppings',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
    ]
