# Generated by Django 2.2.7 on 2024-02-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_toppings_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularpizza',
            name='img',
            field=models.CharField(default='/orders/images/pizza/burger_pizza.jpg', max_length=200),
        ),
        migrations.AddField(
            model_name='sicilianpizza',
            name='img',
            field=models.CharField(default='/orders/images/pizza/morocco_pizza.jpg', max_length=200),
        ),
    ]
