# Generated by Django 2.2.7 on 2024-03-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20240229_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularpizza',
            name='img',
            field=models.CharField(default='/orders/images/pizza/regular/burger_pizza.jpg', max_length=200),
        ),
        migrations.AlterField(
            model_name='sicilianpizza',
            name='img',
            field=models.CharField(default='/orders/images/pizza/sicillian/morocco_pizza.jpg', max_length=200),
        ),
    ]
