# Generated by Django 2.2.7 on 2024-03-05 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20240302_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinnerplatters',
            old_name='large_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='regularpizza',
            old_name='large_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='sicilianpizza',
            old_name='large_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='sub',
            old_name='large_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='dinnerplatters',
            name='small_price',
        ),
        migrations.RemoveField(
            model_name='regularpizza',
            name='small_price',
        ),
        migrations.RemoveField(
            model_name='sicilianpizza',
            name='small_price',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='small_price',
        ),
    ]
